---
  ### Read Me ###
  #  This playbook will install the dcgm nvidia service along with the dcgm-exporter for Prometheus on Ubuntu.

- hosts: all
  remote_user: root
  become: true
  tasks:

  - name: Gather package facts
    package_facts:
      manager: auto

  - name: add key
    apt_key:
      url: "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004-keyring.gpg"
      state: present
    when: '"datacenter-gpu-manager" not in ansible_facts.packages'
    
  - name: add repository
    apt_repository:
      filename: cuda-compute-repo
      repo: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
      state: present
      update_cache: yes
    when: '"datacenter-gpu-manager" not in ansible_facts.packages'
    
  - name: install cuda dcgm (Ubuntu)
    apt:
      name: datacenter-gpu-manager
      state: present
    when: '"datacenter-gpu-manager" not in ansible_facts.packages'
  
  - name: configure systemd to use nvidia-dcgm service
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: nvidia-dcgm.service
    when: '"datacenter-gpu-manager" not in ansible_facts.packages'
  
  - name: copy binary dcgm-exporter
    copy:
      src: dcgm-exporter
      dest: "/usr/bin"
      mode: '0755'
  
  - name: mkdir /etc/dcgm-exporter
    file:
      path: "/etc/dcgm-exporter"
      state: directory
  
  - name: copy default-counters.csv
    copy:
      src: default-counters.csv
      dest: "/etc/dcgm-exporter/default-counters.csv"
  
  - name: copy dcgm-custom-metrics.csv
    copy:
      src: dcgm-custom-metrics.csv
      dest: "/etc/dcgm-exporter/dcgm-custom-metrics.csv"

  - name: copy dcp-metrics-included.csv
    copy:
      src: dcp-metrics-included.csv
      dest: "/etc/dcgm-exporter/dcp-metrics-included.csv"

  - name: install unit file to systemd
    template:
      src: dcgm_exporter.service
      dest: /etc/systemd/system/dcgm_exporter.service

  - name: configure systemd to use service
    systemd:
      daemon_reload: yes
      enabled: yes
      state: started
      name: dcgm_exporter.service